# Generated by Django 4.2.29 on 2026-03-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
