# Generated by Django 4.2.28 on 2026-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='probation',
            name='day30_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probation',
            name='day60_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probation',
            name='day80_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
