# Generated by Django 4.2.28 on 2026-03-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_probation_day30_triggered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_track',
            field=models.CharField(choices=[('biannual', 'Bi-Annual'), ('quarterly', 'Quarterly'), ('both', 'Both (Deduplicated)')], default='biannual', max_length=20),
        ),
    ]
